#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          mba62
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MacBookAir6,2 helpers
# Description:       This script runs various helpers for MacBookAir6,2.
### END INIT INFO

# Author: Ville Korhonen <ville@xd.fi>

DESC="MacBookAir6,2 helpers"
#DAEMON=/usr/sbin/daemonexecutablename

# TODO: Load/save brightness on start/stop

[ -r /etc/default/mba62 ] || exit 0
. /etc/default/mba62

change_device_permissions() {
	for device in ${MBA62_ALL_DEVICES}
	do
		ctrl_file="${device}/brightness"
		if [ -e "${ctrl_file}" ]
		then
			chgrp ${MBA62_BACKLIGHT_GROUP} ${ctrl_file}
			chmod g+w ${ctrl_file}
		fi
	done
}

do_start() {
	change_device_permissions
}

do_stop() {
	echo "OK"
}

exit 0